package uwi.dcit.AgriExpenseTT.lists;

import java.util.ArrayList;
import java.util.Arrays;

/**
 * Created by rcjasmin on 12/1/2016.
 */

public class Crops  {

    // List of Default Crops
    public static  final ArrayList<String> plist = new ArrayList<String>( Arrays.asList(
        "SOYABEAN", "COCOA", "ORANGES","LIME","LEMON","GRAPEFRUIT","TANGERINE","PORTUGAL",
        "COCONUT","CITRUS","GOLDEN APPLE","MANGO","WATERMELON","PAW PAW","PINEAPPLE","SUGARCANE",
        "SORREL","RICE","MAIZE (CORN)", "BREADFRUIT","BANANA","BREADNUT (CHATAIGNE)","CHERRY",
        "CARAMBOLA","PEANUTS","NUTMEG","ANISE SEED","BASIL","BAY LEAF","CELERY","CHIVE","CURRY LEAF",
         "DILL","FENNEL", "MARJORAM","MINT","OREGANO","PARSLEY","ROSEMARY","CULANTRO (SHADON BENI / BANDANIA)",
        "TARRAGON","THYME - FRENCH","THYME - SPANISH","THYME - FINE","BEET","CASSAVA","CUSH CUSH",
        "DASHEEN","EDDOES","GINGER","HORSERADISH","ONIONS","SWEET POTATO","TANNIA","LEREN (TOPI TAMBU)",
        "TUMERIC (SAFFRON)","YAM"));

    public static  final ArrayList<String> toUpdatelist = new ArrayList<String>( Arrays.asList(
            "BHAGI","BORA (BODI) BEAN","BROCCOLI","CARROTS","CABBAGE","CARAILLI",
            "CAULIFLOWER","CHOI SUM (CHINESE CABBAGE)","CHRISTOPHENE","CORN","CUCUMBER","DASHEEN BUSH",
            "GREEN FIG","COWPEA (GUB GUB)","HOT PEPPER","JACK BEAN","JHINGI","LAUKI","LETTUCE","EGGPLANT",
            "RADISH (MOORAI)","OCHRO","PAKCHOY","PIGEON PEAS","PIMENTO PEPPER","PLANTAIN",
            "VINE SPINACH (POI BHAGI)","PUMPKIN","SAIJAN","SATPUTIYA (LOOFAH)","SEIM","STRING BEAN","SQUASH",
            "SWEET PEPPER","TOMATO","WATERCRESS","WING BEAN","ESCALLION","BHAGI","BORA (BODI) BEAN","CARAILLI",
            "CHOI SUM (CHINESE CABBAGE)","CORN","CUCUMBER","DASHEEN BUSH","GREEN FIG","COWPEA (GUB GUB)","JACK BEAN","JHINGI",
            "LAUKI","RADISH (MOORAI)","OCHRO","PAKCHOY","PIMENTO PEPPER","PLANTAIN",
            "VINE SPINACH (POI BHAGI)","PUMPKIN","SAIJAN","SATPUTIYA","SEIM","STRING BEAN",
            "SQUASH","TOMATO","WATERCRESS","WING BEAN","BEET","CUSH CUSH","GINGER","LEREN (TOPI TAMBU)",
            "TUMERIC (SAFFRON)","ANISE SEED","BASIL","BAY LEAF","CELERY","CHIVE","CURRY LEAF",
            "DILL","FENNEL","MARJORAM","MINT","OREGANO","PARSLEY","ROSEMARY","CULANTRO (SHADON BENI / BANDANIA)",
            "TARRAGON","THYME - FRENCH","THYME - SPANISH","THYME - FINE","PAW PAW","PEANUTS",
            "NUTMEG","BANANA","BREADFRUIT","BREADNUT (CHATAIGNE)","CHERRY","CARAMBOLA","PUMPKIN"
    ));
}
